// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKlNu9CKIE2hj3k5DNZmMdFIykFGBu7O4',
    appId: '1:727130604148:web:d7569914deb4d82b2ec721',
    messagingSenderId: '727130604148',
    projectId: 'is381-2024-67a94',
    authDomain: 'is381-2024-67a94.firebaseapp.com',
    storageBucket: 'is381-2024-67a94.firebasestorage.app',
    measurementId: 'G-MSCLR0EVS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP85HzOcDhmPbkzyNJRwa53UbbO6sAlEI',
    appId: '1:727130604148:android:ecdba55b973c87002ec721',
    messagingSenderId: '727130604148',
    projectId: 'is381-2024-67a94',
    storageBucket: 'is381-2024-67a94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe-Bzml6wrlyl_KRw4DJag3FxCvgCnIhc',
    appId: '1:727130604148:ios:61c55678f7e6b4e62ec721',
    messagingSenderId: '727130604148',
    projectId: 'is381-2024-67a94',
    storageBucket: 'is381-2024-67a94.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe-Bzml6wrlyl_KRw4DJag3FxCvgCnIhc',
    appId: '1:727130604148:ios:61c55678f7e6b4e62ec721',
    messagingSenderId: '727130604148',
    projectId: 'is381-2024-67a94',
    storageBucket: 'is381-2024-67a94.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

}