// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ7kFxl4802gRRx2KSnbJG2LkI3coOLdo',
    appId: '1:894257821277:web:e071ef3cffc3dff19b7fb4',
    messagingSenderId: '894257821277',
    projectId: 'levelup-5fc68',
    authDomain: 'levelup-5fc68.firebaseapp.com',
    storageBucket: 'levelup-5fc68.firebasestorage.app',
    measurementId: 'G-866RD650NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7NhBdIw5Uj_u6wAEbw6JKdvb1_csBmzM',
    appId: '1:894257821277:android:2549f43f9f5127a29b7fb4',
    messagingSenderId: '894257821277',
    projectId: 'levelup-5fc68',
    storageBucket: 'levelup-5fc68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtbgQBEPYsC0FQmKVzfkkC97fHJmHQkHY',
    appId: '1:894257821277:ios:7f3970c8c91301779b7fb4',
    messagingSenderId: '894257821277',
    projectId: 'levelup-5fc68',
    storageBucket: 'levelup-5fc68.firebasestorage.app',
    iosBundleId: 'com.example.levelup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtbgQBEPYsC0FQmKVzfkkC97fHJmHQkHY',
    appId: '1:894257821277:ios:7f3970c8c91301779b7fb4',
    messagingSenderId: '894257821277',
    projectId: 'levelup-5fc68',
    storageBucket: 'levelup-5fc68.firebasestorage.app',
    iosBundleId: 'com.example.levelup',
  );

}