name: LevelUp
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  filter_list: ^1.0.3
  flutter_product_card: ^0.0.6
  provider: ^6.1.2
  intl: ^0.17.0
  url_launcher: ^6.0.20
  http: ^1.2.2
  flutter_rating_bar: ^4.0.1
  image_picker : ^0.8.5+3
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  file_picker: ^5.3.3
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
